import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/component/Navbar";
import Footer from "@/component/Footer";
import { WixClientContextProvider } from "@/context/wixContext"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UprisingStreet",
  description: "Generated by shubham",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WixClientContextProvider>
        <NavBar/>
        {children}
        <Footer/>
        </WixClientContextProvider>

        </body>
    </html>
  );
}
